### PR TITLE
remove unicode char from summary

### PR DESCRIPTION
**Pull request by cdeepali**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR removes the unicode char from the `summary `as due to the presence of this character yaml parsing of the packaged `about.json` fails.

### CODE REVIEW

**Comment by ocefpaf** [comment]
No strong feelings and I'm ok removing it, but can you elaborate on the reason for this? Are you experience issues building this recipe with it?

**Comment by cdeepali** [comment]
Thanks @ocefpaf for merging this. 

Issues are not seen during build, but during parsing of packaged `about.json.` Please pardon my ignorance, was there a reason of having it there?

**Comment by ocefpaf** [comment]
> Issues are not seen during build, but during parsing of packaged `about.json.` Please pardon my ignorance, was there a reason of having it there?

It in the original summary and it made in here by either copy-n-paste or our automated tools used to create recipes. I guess most tools we use can parse that so we never really bothered.

**Comment by cdeepali** [comment]
Thanks @ocefpaf. That helps.

**Pull request merged**
